{{- if and .Values.OPERATOR_ENABLED (not .Values.restrictedEnvironment) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ cat .Values.NAMESPACE "-" .Values.SERVICE_NAME | nospace | trunc 63 | trimSuffix "-" }}'
  labels:
    app.kubernetes.io/instance: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ cat .Values.NAMESPACE "-" .Values.SERVICE_NAME | nospace | trunc 63 | trimSuffix "-" }}'
subjects:
  - kind: ServiceAccount
    name: '{{ .Values.SERVICE_NAME }}'
    namespace: '{{ .Values.NAMESPACE }}'
{{- end }}
