---
apiVersion: v1
kind: ConfigMap
metadata:
  name: replication-configuration
  labels:
    managed-by: Helm
    app.kubernetes.io/managed-by: Helm
    netcracker.cloud/part-of: disaster-recovery
    netcracker.cloud/used-by: cluster-replicator
  annotations:
    meta.helm.sh/release-name: {{ .Values.SERVICE_NAME }}
    meta.helm.sh/release-namespace: {{ .Values.NAMESPACE }}
data: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-dr-profile
  labels:
    managed-by: Helm
    app.kubernetes.io/managed-by: Helm
    netcracker.cloud/part-of: disaster-recovery
    netcracker.cloud/used-by: cluster-replicator
    profiles-package-type: default
  annotations:
    meta.helm.sh/release-name: {{ .Values.SERVICE_NAME }}
    meta.helm.sh/release-namespace: {{ .Values.NAMESPACE }}
data:
  hot-standby: |-
    default-replicas: 1
  cold-standby: |-
    default-replicas: 0
