---
apiVersion: v1
kind: Secret
metadata:
  name: maas-instance-registrations
  labels:
    app.kubernetes.io/instance: {{ .Values.SERVICE_NAME }}
    app.kubernetes.io/managed-by: "helm"
    deployment.netcracker.com/sessionId: {{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}
data:
{{ if .Values.MAAS_KAFKA_INSTANCE_BODY }}
  maas-kafka-instance-body: {{ .Values.MAAS_KAFKA_INSTANCE_BODY | b64enc }}
{{ end }}
{{ if .Values.MAAS_KAFKA_INSTANCE_BODY_2 }}
  maas-kafka-instance-body-2: {{ .Values.MAAS_KAFKA_INSTANCE_BODY_2 | b64enc }}
{{ end }}
{{ if .Values.MAAS_RABBIT_INSTANCE_BODY }}
  maas-rabbit-instance-body: {{ .Values.MAAS_RABBIT_INSTANCE_BODY | b64enc }}
{{ end }}
{{ if .Values.MAAS_RABBIT_INSTANCE_BODY_2 }}
  maas-rabbit-instance-body-2: {{ .Values.MAAS_RABBIT_INSTANCE_BODY_2 | b64enc }}
{{ end }}


---
apiVersion: v1
kind: Secret
metadata:
  name: maas-accounts
  labels:
    app.kubernetes.io/instance: {{ .Values.SERVICE_NAME }}
    app.kubernetes.io/managed-by: "helm"
    deployment.netcracker.com/sessionId: {{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}
data:
  manager-username:  {{ .Values.MAAS_ACCOUNT_MANAGER_USERNAME | b64enc }}
  manager-password: {{ .Values.MAAS_ACCOUNT_MANAGER_PASSWORD | b64enc }}
  deployer-username: {{ .Values.MAAS_DEPLOYER_CLIENT_USERNAME | b64enc }}
  deployer-password: {{ .Values.MAAS_DEPLOYER_CLIENT_PASSWORD | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.SERVICE_NAME }}-env-variables
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-250"
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
  labels:
    app.kubernetes.io/instance: {{ .Values.SERVICE_NAME }}
    deployment.netcracker.com/sessionId: {{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}
    app.kubernetes.io/part-of: maas
stringData:
  NAMESPACE: {{ .Values.NAMESPACE | default "" }}
  SERVICE_NAME: {{ .Values.SERVICE_NAME | quote }}
  DB_POSTGRESQL_ADDRESS: {{ .Values.DB_POSTGRESQL_ADDRESS | quote }}
  DB_POSTGRESQL_DATABASE: {{ .Values.DB_POSTGRESQL_DATABASE | quote }}
  DB_POSTGRESQL_USERNAME: {{ .Values.DB_POSTGRESQL_USERNAME | quote }}
  DB_POSTGRESQL_PASSWORD: {{ .Values.DB_POSTGRESQL_PASSWORD | quote }}
  DB_POSTGRESQL_TLS_ENABLED: {{ .Values.DB_POSTGRESQL_TLS_ENABLED | default "false" | quote }}
  DB_POSTGRESQL_TLS_SKIPVERIFY: {{ .Values.DB_POSTGRESQL_TLS_SKIPVERIFY | default "false" | quote }}
  DBAAS_LODB_PER_NAMESPACE_AUTOBALANCE_RULES: {{ .Values.DBAAS_LODB_PER_NAMESPACE_AUTOBALANCE_RULES | quote }}
  API_DBAAS_ADDRESS:  {{ .Values.API_DBAAS_ADDRESS | quote }}
  DBAAS_AGGREGATOR_ADDRESS:  {{ .Values.DBAAS_AGGREGATOR_ADDRESS | quote }}
  DBAAS_CLUSTER_DBA_CREDENTIALS_USERNAME:  {{ .Values.DBAAS_CLUSTER_DBA_CREDENTIALS_USERNAME | quote }}
  DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD:  {{ .Values.DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD | quote }}
  MAAS_ACCOUNT_MANAGER_USERNAME: {{ .Values.MAAS_ACCOUNT_MANAGER_USERNAME | quote }}
  MAAS_ACCOUNT_MANAGER_PASSWORD: {{ .Values.MAAS_ACCOUNT_MANAGER_PASSWORD | quote }}
