---
apiVersion: batch/v1
kind: Job
metadata:
  name: validation-hook-{{ .Values.SERVICE_NAME }}
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-weight: "-240"
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
  labels:
    app.kubernetes.io/instance: {{ .Values.SERVICE_NAME }}
    deployment.netcracker.com/sessionId: {{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}
    app.kubernetes.io/part-of: maas
spec:
  backoffLimit: 5
  template:
    metadata:
      name: validation-hook-{{ .Values.SERVICE_NAME }}
    spec:
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 10
      volumes:
        - name: validation-secrets
          secret:
            secretName: {{ .Values.SERVICE_NAME }}-env-variables
            defaultMode: 0400
      containers:
      - name: validation-hook-{{ .Values.SERVICE_NAME }}
        image: {{ .Values.DECLARATIVE_HOOK_IMAGE }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: validation-secrets
            mountPath: /var/run/secrets/maas/validation
            readOnly: true
      restartPolicy: Never
