{
 "title": "Messaging as a Service (MaaS)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "service_name",
    "label": "Service name",
    "query": "label_values(go_info{namespace=\"$namespace\",}, container)"
   },
   {
    "name": "pod_name",
    "label": "Pod name",
    "query": "label_values(go_info{namespace=\"$namespace\", container=\"$service_name\"}, pod)"
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "kafka_instances",
    "query": {
     "query": "label_values(maas_health_broker_status{broker_type=\"Kafka\"},broker_id)"
    }
   },
   {
    "name": "rabbit_instances",
    "query": {
     "query": "label_values(maas_health_broker_status{broker_type=\"RabbitMQ\"},broker_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_running{exported_namespace=\"$namespace\", exported_pod=\"$pod_name\", exported_pod!~\".*deploy\", container=\"$service_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{container=\"$service_name\", pod=\"$pod_name\", namespace=\"$namespace\"} \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DR Mode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "maas_db_dr_mode {container=\"$service_name\", pod=\"$pod_name\", namespace=\"$namespace\"} \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Master DB Availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "maas_health_is_master_db_alive{container=\"$service_name\", pod=\"$pod_name\", namespace=\"$namespace\"} \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open FD Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Routines Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{container=\"$service_name\", pod=\"$pod_name\", namespace=\"$namespace\"} \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Summary of CPU usage by pod $pod_name.\n\nThe red line shows limit of CPUs usage for the process.\n\nThe values is indicated in Millicores. It is a special Kubernates metric means CPU core split into 1000 units.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "usage",
     "expr": "rate(container_cpu_usage_seconds_total{container=\"$service_name\", pod=\"$pod_name\", namespace=\"$namespace\"}[$inter])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "usage",
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "limit",
     "expr": "kube_pod_container_resource_limits_cpu_cores{container=\"$service_name\", exported_pod=\"$pod_name\", exported_namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "limit",
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "request",
     "expr": "kube_pod_container_resource_requests_cpu_cores{container=\"$service_name\", exported_pod=\"$pod_name\", exported_namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "request",
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    }
   ]
  },
  {
   "title": "Commited Memory",
   "type": "timeseries",
   "description": "The amount of used memory",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Heap",
     "expr": "kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\", container=\"$service_name\", exported_pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Limit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Heap",
     "expr": "kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\", container=\"$service_name\", exported_pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Non Heap : Code Cache",
     "expr": "container_memory_max_usage_bytes{namespace=\"$namespace\", container=\"$service_name\", pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory $pod_name",
   "type": "timeseries",
   "description": "Information about resident and virtual memory",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Resident Memory",
     "expr": "process_resident_memory_bytes{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Resident Memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Virtual Memory",
     "expr": "process_virtual_memory_bytes{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Virtual Memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "timeseries",
   "description": "The open file descriptor count",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 14 },
   "repeat": "pod_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "open",
     "expr": "process_max_fds{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Limit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "open",
     "expr": "process_open_fds {container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Go Routines Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "open",
     "expr": "go_goroutines{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Routines",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "open",
     "expr": "go_threads {container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Go Process Memory Details ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "open",
       "expr": "go_memstats_heap_sys_bytes{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "allocated",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "open",
       "expr": "go_memstats_heap_inuse_bytes {container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "in use",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Off-Heap",
     "type": "timeseries",
     "description": "Memory that uses Go process outside main heap ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "open",
       "expr": "go_memstats_gc_sys_bytes{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "gc meta",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "open",
       "expr": "go_memstats_mspan_sys_bytes{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "mspan",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "open",
       "expr": "go_memstats_mcache_sys_bytes{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "mcache",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "open",
       "expr": "go_memstats_buck_hash_sys_bytes{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "pprof",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "open",
       "expr": "go_memstats_other_sys_bytes{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "other",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "open",
       "expr": "go_memstats_stack_sys_bytes{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "stack",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Allocated Objects Count ",
     "type": "timeseries",
     "description": "Number of allocated objects",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "open",
       "expr": "go_memstats_heap_objects {container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "__auto",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Freed Objects Count ",
     "type": "timeseries",
     "description": "Number of allocated objects",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "open",
       "expr": "rate(go_memstats_frees_total {container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$__interval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "__auto",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC Duration",
     "type": "timeseries",
     "description": "Time spent by GC to collect your shit",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "open",
       "expr": "rate(go_gc_duration_seconds_sum{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$__interval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "gc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Serving Requests Rate  ",
     "type": "timeseries",
     "description": "Shows amount of successful requests to different URLs per second",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "repeat": "pod_name",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$tag_path",
       "expr": "sum(rate(http_requests_total{container=\"$service_name\", namespace=\"$namespace\", status_code!~\"5..\", pod=\"$pod_name\"}[$__interval])) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "success",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(rate(http_requests_total{container=\"$service_name\", namespace=\"$namespace\", status_code=~\"5..\", pod=\"$pod_name\"}[$__interval])) OR on() vector(0)",
       "legendFormat": "failures"
      }
     ]
    },
    {
     "title": "Request Serving Time (non 500)",
     "type": "heatmap",
     "description": "Shows amount of successful requests to different URLs per second",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "alias": "$tag_path",
       "expr": "sum by(le) (\r\n  rate(http_request_duration_seconds_bucket{container=\"$service_name\", namespace=\"$namespace\", status_code!~\"5..\", pod=\"$pod_name\"}[$__interval])\r\n  )",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{le}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Database Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Pool ",
     "type": "timeseries",
     "description": "limit: Maximum number of open connections to the database\nopen: The number of established connections both in use and idle\nin use: The number of connections currently in use\n",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "go_sql_stats_connections_max_open{container=\"$service_name\", pod=\"$pod_name\", namespace=\"$namespace\"}",
       "legendFormat": "limit"
      },
      {
       "expr": "go_sql_stats_connections_open{container=\"$service_name\", pod=\"$pod_name\", namespace=\"$namespace\"}",
       "legendFormat": "open"
      },
      {
       "expr": "go_sql_stats_connections_in_use{container=\"$service_name\", pod=\"$pod_name\", namespace=\"$namespace\"}",
       "legendFormat": "in use"
      }
     ]
    },
    {
     "title": "Wait time for available connection from pool",
     "type": "timeseries",
     "description": "The time blocked waiting for a new connection.",
     "gridPos": { "h": 8, "w": 5, "x": 7, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(go_sql_stats_connections_blocked_seconds{container=\"$service_name\", pod=\"$pod_name\", namespace=\"$namespace\"}[$__rate_interval])",
       "legendFormat": "blocked"
      }
     ]
    },
    {
     "title": "Master SQL Requests Rate",
     "type": "timeseries",
     "description": "The number of SQL requests per second are executed on master database  ",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(maas_db_request_count{type=\"master\", container=\"$service_name\", pod=\"$pod_name\", namespace=\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Replica SQL Requests Rate",
     "type": "timeseries",
     "description": "The number of SQL requests per second are executed on in memory failover replica database ",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(maas_db_request_count{type=\"replica\", container=\"$service_name\", pod=\"$pod_name\", namespace=\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "SQL Requests Execution Time",
     "type": "heatmap",
     "description": "The number of SQL requests per second are executed on in memory failover replica database ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "rate(maas_db_sql_executions_bucket{container=\"$service_name\", pod=\"$pod_name\", namespace=\"$namespace\"}[$__interval])",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Message Broker Statuses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Instances ${kafka_instances}",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 73 },
     "repeat": "kafka_instances",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "maas_health_broker_status{broker_type=\"Kafka\", broker_id=\"$kafka_instances\", container=\"$service_name\", pod=\"$pod_name\", namespace=\"$namespace\"} \r\n",
       "legendFormat": "Kafka: {{broker_id}}"
      }
     ]
    },
    {
     "title": "Rabbit Instance: ${rabbit_instances}",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 77 },
     "repeat": "rabbit_instances",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "maas_health_broker_status{broker_type=\"RabbitMQ\", broker_id=\"$rabbit_instances\", container=\"$service_name\", pod=\"$pod_name\", namespace=\"$namespace\"} \r\n",
       "legendFormat": "Kafka: {{broker_id}}"
      }
     ]
    }
   ]
  }
 ]
}