name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  prepare-variables:
    runs-on: ubuntu-latest
    steps:
      - id: tag_build_number
        run: echo "tag=$(echo ${{ github.head_ref || github.ref_name }} | tr -cs 'a-zA-Z0-9' '-')$(date +'%Y%m%d%H%M%S')-${{ github.run_number }}" >> $GITHUB_OUTPUT
      - id: tag_snapshot
        run: echo "tag=$(echo ${{ github.head_ref || github.ref_name }} | tr -cs 'a-zA-Z0-9' '-')snapshot" >> $GITHUB_OUTPUT
    outputs:
      tag_build_number: ${{ steps.tag_build_number.outputs.tag }}
      tag_snapshot: ${{ steps.tag_snapshot.outputs.tag }}
      repo: ${{ steps.repo.outputs.repo }}
  build:
    runs-on: ubuntu-latest
    needs: prepare-variables
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Test with coverage
      run: |
        cd maas-service
        go test -v ./... -coverprofile coverage.out

    - name: Upload coverage report to SonarCloud
      uses: SonarSource/sonarqube-scan-action@v5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
       args: >
         -Dproject.settings=maas-service/sonar-project.properties
         -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
         -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
         -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}
         -Dsonar.go.coverage.reportPaths=maas-service/coverage.out

    - name: Build and Publish Docker Image
      uses: netcracker/qubership-workflow-hub/actions/docker-action@c07a5bf430a3c0120e189e6b54061b9bb8dde362
      with:
        ref: ${{ github.head_ref || github.ref_name }}
        tags: ${{ needs.prepare-variables.outputs.tag_snapshot }},${{ needs.prepare-variables.outputs.tag_build_number }}
        platforms: linux/amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}