name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Test with coverage
      run: |
        cd maas-service
        go test -v ./... -coverprofile coverage.out

    - name: Upload coverage report to SonarCloud
      uses: SonarSource/sonarqube-scan-action@v5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
       args: >
         -Dproject.settings=maas-service/sonar-project.properties
         -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
         -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
         -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}
         -Dsonar.go.coverage.reportPaths=maas-service/coverage.out

    - name: Build and Publish Docker Image
      uses: netcracker/qubership-workflow-hub/actions/docker-action@main
      with:
        ref: ${{ github.head_ref || github.ref_name }}
        platforms: linux/amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}