name: '[MaaS] Go build'

on:
  push:
    paths:
      - 'maas/**'
      - 'maas-integration-tests/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'maas/**'
      - 'maas-integration-tests/**'

jobs:
  build:
    uses: netcracker/qubership-core-infra/.github/workflows/generic-go-build.yaml@8668020927f2a84d8d096a359c719c3c3a403520 # v2.5.0
    with:
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      go-module-dir: maas/maas-service
      skip-docker: true
    secrets: inherit

  integration-tests:
    uses: netcracker/qubership-core-infra/.github/workflows/generic-maven-build.yaml@8668020927f2a84d8d096a359c719c3c3a403520 # v2.5.0
    with:
      maven-command: ${{ github.event_name == 'pull_request' && 'verify' || 'deploy' }}
      skip-docker: true
    secrets: inherit

  docker-build:
    needs: [build, integration-tests]
    uses: netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@8668020927f2a84d8d096a359c719c3c3a403520 # v2.5.0
    with:
      dry-run: false
      config-filename: "maas---docker-dev-config.json"
